#!/usr/bin/env bash
release_bindir="$(dirname "${BASH_SOURCE[0]}")"
release_bindir_abs="$("$release_bindir"/../libexec/realpath "$release_bindir")"
release_topdir_abs="$("$release_bindir"/../libexec/realpath "$release_bindir/..")"
export PATH="$release_bindir_abs:$PATH"
exec "$release_topdir_abs"/libexec/nextpnr-ice40 "$@"
