# Packaging and Releasing the Tools-oss-cad-suite apio package.
# The versions of the upstream oss-cad-suite packages and the
# version of the packages release here are set in build.sh.

name: build-and-release

# Manual activation
on: [workflow_dispatch]

jobs:

  # -- Build packages for all supported architectures and
  # -- export them in a release.
  build-and-release:

    runs-on: ubuntu-22.04

    steps:
      # -- Checkout the repo
      - name: Checkout!
        uses: actions/checkout@v4

      # -- Build the package for linux_x86_64
      - name: Build package [linux_x86_64]
        run: |
          ./build.sh linux_x86_64
          version=$(cat VERSION_BUILD)
          echo "VERSION: $version"
          echo "VERSION=$version" >> $GITHUB_ENV

      # -- Build the package for linux_aarch64
      - name: Build package [linux_aarch64]
        run: |
          ./build.sh linux_aarch64

      # -- Build the package for darwin
      - name: Build package darwin
        run: |
          ./build.sh darwin

      # -- Build the package for darwin_arm64
      - name: Build package [darwin_arm64]
        run: |
          ./build.sh darwin_arm64

 
      # -- Build the package for windows_amd64
      - name: Build package [windows_amd64]
        run: |
          ./build.sh windows_amd64

      #-- Create the Release and upload files
      - name: Create the Release and upload files
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          tag_name: v${{ env.VERSION }}
          body: A new release (Draft)
          files: |
            _packages/tools-oss-cad-suite-linux_x86_64-${{ env.VERSION }}.tar.gz
            _packages/tools-oss-cad-suite-linux_aarch64-${{ env.VERSION }}.tar.gz
            _packages/tools-oss-cad-suite-darwin-${{ env.VERSION }}.tar.gz
            _packages/tools-oss-cad-suite-darwin_arm64-${{ env.VERSION }}.tar.gz
            _packages/tools-oss-cad-suite-windows_amd64-${{ env.VERSION }}.tar.gz


