# Packaging and Releasing the Tools-oss-cad-suite apio package

name: Release

# Manual activation
on: [workflow_dispatch]

jobs:

  # -- Building Linux_x86_64
  # -- It creates the package tools-oss-cad-suite-linux-x86-64-20210627.tar.gz
  build-Linux_x86_64:

    runs-on: ubuntu-20.04

    steps:
      # -- Checkout the repo
      - name: Checkout!
        uses: actions/checkout@v2

      # -- Build the package for LINUX
      - name: Build Script (Linux_x86_64)
        run: |
          ./build.sh linux_x86_64
          version=$(cat VERSION)
          echo "VERSION: $version"
          echo "VERSION=$version" >> $GITHUB_ENV

      # -- Build the package for MAC
      - name: Build Script (MAC)
        run: |
          ./build.sh darwin

      # -- Build the package for WINDOWS
      - name: Build Script (Windows_amd64)
        run: |
          ./build.sh windows_amd64

      #-- Create the Release
      - name: Create the Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: |
            A new release
          draft: true
          prerelease: false

      - name: Upload Linux_64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: _packages/tools-oss-cad-suite-linux_x86_64-${{ env.VERSION }}.tar.gz
          asset_name: tools-oss-cad-suite-linux_x86_64-${{ env.VERSION }}.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload MAC Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: _packages/tools-oss-cad-suite-darwin-${{ env.VERSION }}.tar.gz
          asset_name: tools-oss-cad-suite-darwin-${{ env.VERSION }}.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload Window Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: _packages/tools-oss-cad-suite-windows_amd64-${{ env.VERSION }}.tar.gz
          asset_name: tools-oss-cad-suite-windows_amd64-${{ env.VERSION }}.tar.gz
          asset_content_type: application/tar+gzip


